### PR TITLE
Add user agent

### PR DESCRIPTION
**Pull request by ballon3**

### CODE REVIEW

**Review by jakelee8 — APPROVED** [review]

**Comment by ptescher** [comment]
Might want to fall back to something like "bitski-rs" if those env are not there.

**Comment by ptescher** [comment]
oh unless they are always there

**Comment by jakelee8** [comment]
Those env are set at build time, so they will be hardcoded to the crate values.

**Comment by jakelee8** [comment]
To get them from the env, use `std::env::var`

**Comment by ballon3** [comment]
Need to push token-api with the new commit hash for this pr once its merged also

**Review by ptescher — APPROVED** [review]

**Comment by ballon3** [comment]
> 

are you indicating I need to import this, as it seems to compile or is this just a recommendation/comment on the CARGO env vars

**Pull request merged**
